package patch

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aws/eks-cross-region-nodes/pkg/discovery"
	"sigs.k8s.io/yaml"
)

var (
	kubeletEnvFile    = "/etc/eks/kubelet/environment"
	kubeletConfigFile = "/etc/kubernetes/kubelet/config.json"
	kubeconfigFile    = "/var/lib/kubelet/kubeconfig"
	// credHelperPath is where the cross-account AssumeRole credential helper is written.
	credHelperPath = "/etc/kubernetes/xrn/get-cluster-token.sh"
)

func setEnvFile(path string)        { kubeletEnvFile = path }
func setConfigFile(path string)     { kubeletConfigFile = path }
func setKubeconfigFile(path string) { kubeconfigFile = path }
func setCredHelperPath(path string) { credHelperPath = path }

// CrossAccount configures cross-account kubelet credentials. When Enabled, the kubelet's
// kubeconfig exec block is rewritten to call an AssumeRole credential helper instead of
// calling `aws eks get-token` directly with the instance role (which can't authenticate to
// a cluster in another account).
type CrossAccount struct {
	Enabled          bool
	SatelliteRoleARN string // cluster-account role the instance assumes (XrnSatelliteNodeRole)
	ExternalID       string // optional sts:ExternalId
}

// ProviderID format identifiers (value of --provider-id-format).
const (
	// ProviderIDHybrid is the default: eks-hybrid:///<region>/<cluster>/<instance-id>.
	// Required so the EKS CCM does not reap the node (validated 2026-06-06). NOT parseable
	// by the cluster-autoscaler AWS provider, which expects aws:///<az>/<id> — CA cannot
	// match/autoscale nodes with this format.
	ProviderIDHybrid = "eks-hybrid"
	// ProviderIDAWS is the standard EC2 format: aws:///<az>/<instance-id>. Parseable by
	// cluster-autoscaler. EXPERIMENTAL for satellite nodes: only safe if --cloud-provider=""
	// (empty) keeps the CCM lifecycle controller from reaping the node despite the aws:/// id.
	// See experiment/aws-providerid-ca-compat.
	ProviderIDAWS = "aws"
)

// ApplyAll applies the cross-region kubelet patches. If xacct is non-nil and Enabled, it
// installs the AssumeRole credential helper and points the kubeconfig at it; otherwise it
// applies the same-account region rewrite (unchanged behavior). providerIDFormat selects the
// providerID written to the kubelet config (ProviderIDHybrid default, or ProviderIDAWS).
func ApplyAll(ctx context.Context, cluster *discovery.ClusterInfo, node *discovery.NodeMetadata, xacct *CrossAccount, providerIDFormat string) error {
	if err := patchKubeletEnvironment(cluster, node); err != nil {
		return fmt.Errorf("patching kubelet environment: %w", err)
	}
	if err := patchProviderID(cluster, node, providerIDFormat); err != nil {
		return fmt.Errorf("patching providerID: %w", err)
	}
	if xacct != nil && xacct.Enabled {
		if err := installCredentialHelper(cluster, node, xacct); err != nil {
			return fmt.Errorf("installing cross-account credential helper: %w", err)
		}
	} else {
		if err := patchKubeconfig(cluster, node); err != nil {
			return fmt.Errorf("patching kubeconfig region: %w", err)
		}
	}
	return nil
}

// RenderCredentialHelper returns the bash script that AssumeRole's into the cluster-account
// satellite role (session name = instance ID, so the kubelet identity is system:node:<id>)
// and execs `aws eks get-token`. Pure function — no I/O.
func RenderCredentialHelper(clusterName, clusterRegion, satelliteRoleARN, externalID string) string {
	externalIDArg := ""
	if externalID != "" {
		externalIDArg = " --external-id " + externalID
	}
	return `#!/bin/bash
set -euo pipefail
# Cross-account kubelet credential helper (generated by xrn-install).
# AssumeRole into the cluster-account satellite role using the EC2 instance role, with the
# session name set to the instance ID so the EKS-issued identity is system:node:<instance-id>.
TOKEN=$(curl -sf -m 5 -X PUT http://169.254.169.254/latest/api/token -H 'X-aws-ec2-metadata-token-ttl-seconds: 60')
INSTANCE_ID=$(curl -sf -m 5 -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
CREDS=$(aws sts assume-role --region ` + clusterRegion + ` --role-arn ` + satelliteRoleARN + externalIDArg + ` --role-session-name "$INSTANCE_ID" --duration-seconds 3600 --output json)
export AWS_ACCESS_KEY_ID=$(echo "$CREDS" | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo "$CREDS" | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$CREDS" | jq -r .Credentials.SessionToken)
exec aws eks get-token --cluster-name ` + clusterName + ` --region ` + clusterRegion + `
`
}

func patchKubeletEnvironment(cluster *discovery.ClusterInfo, node *discovery.NodeMetadata) error {
	data, err := os.ReadFile(kubeletEnvFile)
	if err != nil {
		return fmt.Errorf("reading %s: %w", kubeletEnvFile, err)
	}
	content := string(data)

	// 1. cloud-provider=external → cloud-provider= (empty)
	content = strings.Replace(content, "--cloud-provider=external", "--cloud-provider=", 1)

	// 2. hostname-override: replace whatever nodeadm set with instance ID
	if idx := strings.Index(content, "--hostname-override="); idx >= 0 {
		end := strings.IndexByte(content[idx:], ' ')
		if end == -1 {
			end = len(content) - idx
		}
		old := content[idx : idx+end]
		content = strings.Replace(content, old, "--hostname-override="+node.InstanceID, 1)
	}

	// 3. Append topology labels to existing --node-labels
	zoneLabel := "topology.kubernetes.io/zone=" + node.AvailabilityZone
	regionLabel := "topology.kubernetes.io/region=" + node.Region
	if idx := strings.Index(content, "--node-labels="); idx >= 0 {
		// Find the end of the --node-labels value (next space or EOL)
		labelStart := idx + len("--node-labels=")
		end := strings.IndexByte(content[labelStart:], ' ')
		if end == -1 {
			end = len(content) - labelStart
		}
		existingLabels := content[labelStart : labelStart+end]
		if !strings.Contains(existingLabels, "topology.kubernetes.io/zone") {
			newLabels := existingLabels + "," + zoneLabel + "," + regionLabel
			content = content[:labelStart] + newLabels + content[labelStart+end:]
		}
	}

	return os.WriteFile(kubeletEnvFile, []byte(content), 0644)
}

func patchProviderID(cluster *discovery.ClusterInfo, node *discovery.NodeMetadata, format string) error {
	data, err := os.ReadFile(kubeletConfigFile)
	if err != nil {
		return fmt.Errorf("reading %s: %w", kubeletConfigFile, err)
	}

	var config map[string]interface{}
	if err := json.Unmarshal(data, &config); err != nil {
		return fmt.Errorf("parsing kubelet config JSON: %w", err)
	}

	providerID, err := RenderProviderID(format, cluster, node)
	if err != nil {
		return err
	}
	config["providerID"] = providerID

	out, err := json.MarshalIndent(config, "", "    ")
	if err != nil {
		return fmt.Errorf("marshaling kubelet config: %w", err)
	}

	return os.WriteFile(kubeletConfigFile, out, 0644)
}

// RenderProviderID builds the providerID string for the given format. Pure function.
//   - ProviderIDHybrid: eks-hybrid:///<cluster-region>/<cluster-name>/<instance-id>
//   - ProviderIDAWS:    aws:///<availability-zone>/<instance-id>
func RenderProviderID(format string, cluster *discovery.ClusterInfo, node *discovery.NodeMetadata) (string, error) {
	switch format {
	case "", ProviderIDHybrid:
		return fmt.Sprintf("eks-hybrid:///%s/%s/%s", cluster.Region, cluster.Name, node.InstanceID), nil
	case ProviderIDAWS:
		if node.AvailabilityZone == "" {
			return "", fmt.Errorf("provider-id-format=aws requires the node availability zone, which is empty")
		}
		return fmt.Sprintf("aws:///%s/%s", node.AvailabilityZone, node.InstanceID), nil
	default:
		return "", fmt.Errorf("unknown provider-id-format %q (want %q or %q)", format, ProviderIDHybrid, ProviderIDAWS)
	}
}

// patchKubeconfig rewrites the region the kubelet's get-token exec plugin presigns its STS
// token for, from the node's local region (which nodeadm fills in from IMDS) to the cluster's
// home region. SigV4 signatures are region-pinned and the home-region EKS authenticator only
// accepts a token presigned for its own region, so a satellite node otherwise can't authenticate.
//
// The rewrite is anchored to the `--region` argument specifically (not the first quoted region
// string anywhere in the file): it parses the kubeconfig YAML, walks to the exec args list, and
// overwrites the value following `--region`. A positional/first-match rewrite would corrupt the
// file if the local region appeared earlier — e.g. in the cluster name or the server URL
// (https://<id>.<region>.eks.amazonaws.com). node is unused; the target is always cluster.Region.
func patchKubeconfig(cluster *discovery.ClusterInfo, _ *discovery.NodeMetadata) error {
	data, err := os.ReadFile(kubeconfigFile)
	if err != nil {
		return fmt.Errorf("reading %s: %w", kubeconfigFile, err)
	}

	var doc map[string]interface{}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("parsing kubeconfig YAML: %w", err)
	}

	args, err := execArgs(doc)
	if err != nil {
		return err
	}
	if !rewriteRegionArg(args, cluster.Region) {
		return fmt.Errorf("no --region argument found in kubelet kubeconfig exec args")
	}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshaling kubeconfig: %w", err)
	}
	return os.WriteFile(kubeconfigFile, out, 0644)
}

// execArgs navigates a parsed kubeconfig to users[0].user.exec.args and returns the slice
// (mutating its elements mutates doc, since slices are reference types).
func execArgs(doc map[string]interface{}) ([]interface{}, error) {
	users, ok := doc["users"].([]interface{})
	if !ok || len(users) == 0 {
		return nil, fmt.Errorf("kubeconfig has no users entry")
	}
	user0, ok := users[0].(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("kubeconfig users[0] is not a mapping")
	}
	userBlock, ok := user0["user"].(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("kubeconfig users[0].user is not a mapping")
	}
	exec, ok := userBlock["exec"].(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("kubeconfig users[0].user.exec is not a mapping")
	}
	args, ok := exec["args"].([]interface{})
	if !ok {
		return nil, fmt.Errorf("kubeconfig exec has no args list")
	}
	return args, nil
}

// rewriteRegionArg finds the `--region` entry in the exec args and sets the value that follows
// it to region. Also handles the combined `--region=VALUE` form. Returns true if it rewrote a
// value, false if no `--region` argument was present.
func rewriteRegionArg(args []interface{}, region string) bool {
	for i := 0; i < len(args); i++ {
		s, ok := args[i].(string)
		if !ok {
			continue
		}
		if s == "--region" && i+1 < len(args) {
			args[i+1] = region
			return true
		}
		if strings.HasPrefix(s, "--region=") {
			args[i] = "--region=" + region
			return true
		}
	}
	return false
}

// installCredentialHelper writes the AssumeRole helper script and rewrites the kubelet
// kubeconfig's exec credential plugin to invoke it. Used only on cross-account nodes, where
// the instance role can't authenticate directly to the cluster-account EKS API.
func installCredentialHelper(cluster *discovery.ClusterInfo, node *discovery.NodeMetadata, xacct *CrossAccount) error {
	if xacct.SatelliteRoleARN == "" {
		return fmt.Errorf("cross-account requires a satellite role ARN")
	}

	// 1. Write the helper script (executable).
	script := RenderCredentialHelper(cluster.Name, cluster.Region, xacct.SatelliteRoleARN, xacct.ExternalID)
	if err := os.MkdirAll(filepath.Dir(credHelperPath), 0755); err != nil {
		return fmt.Errorf("creating helper dir: %w", err)
	}
	if err := os.WriteFile(credHelperPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("writing credential helper %s: %w", credHelperPath, err)
	}

	// 2. Rewrite the kubeconfig exec block to call the helper.
	if err := rewriteKubeconfigExec(credHelperPath); err != nil {
		return fmt.Errorf("rewriting kubeconfig exec: %w", err)
	}
	return nil
}

// rewriteKubeconfigExec replaces the kubelet kubeconfig's user exec credential plugin so it
// runs the given command (the AssumeRole helper) instead of calling `aws eks get-token`
// directly. Preserves everything else in the kubeconfig.
func rewriteKubeconfigExec(command string) error {
	data, err := os.ReadFile(kubeconfigFile)
	if err != nil {
		return fmt.Errorf("reading %s: %w", kubeconfigFile, err)
	}

	var doc map[string]interface{}
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("parsing kubeconfig YAML: %w", err)
	}

	users, ok := doc["users"].([]interface{})
	if !ok || len(users) == 0 {
		return fmt.Errorf("kubeconfig has no users entry to patch")
	}
	user0, ok := users[0].(map[string]interface{})
	if !ok {
		return fmt.Errorf("kubeconfig users[0] is not a mapping")
	}
	userBlock, ok := user0["user"].(map[string]interface{})
	if !ok {
		userBlock = map[string]interface{}{}
		user0["user"] = userBlock
	}
	userBlock["exec"] = map[string]interface{}{
		"apiVersion":         "client.authentication.k8s.io/v1beta1",
		"command":            command,
		"interactiveMode":    "Never",
		"provideClusterInfo": false,
	}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshaling kubeconfig: %w", err)
	}
	return os.WriteFile(kubeconfigFile, out, 0644)
}
